development:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_development
  user: octo
  password: 'oct0rul3z4ever'

test:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_test
  user: octo
  password: 'oct0rul3z4ever'

production:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell
  pool: 10
  min_messages: warning
  user: octo
  password: 'oct0rul3z4ever'
