development:
  adapter: postgresql
  encoding: unicode
  database: octoshell_big_devel
  user: octo
  password: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_test
  user: octo
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: octoshell_big_devel
  pool: 10
  min_messages: warning
  user: octo
  password: 1234
